CREATE DATABASE [HavanLabs]

USE [HavanLabs]

CREATE TABLE Cliente(
	ID		BIGINT			NOT NULL PRIMARY KEY,
	Codigo	VARCHAR(16)		NOT NULL,
	CPF		VARCHAR(11)		NOT NULL UNIQUE
)

CREATE TABLE Usuario(
	ID		BIGINT			NOT NULL PRIMARY KEY,
	Codigo	VARCHAR(8)		NOT NULL,
	Nome	VARCHAR(128)	NOT NULL
)

CREATE TABLE TicketSituacao(
	ID		SMALLINT	NOT NULL PRIMARY KEY,
	Nome	VARCHAR(64)	NOT NULL
)

CREATE TABLE Ticket(
	ID					BIGINT		NOT NULL	PRIMARY KEY,
	IdUsuarioAbertura	BIGINT		NOT NULL	FOREIGN KEY REFERENCES Usuario(Id),
	IdUsuarioConclusao	BIGINT					FOREIGN KEY REFERENCES Usuario(Id),
	IdCliente			BIGINT					FOREIGN KEY REFERENCES Cliente(Id),
	IdSituacao			SMALLINT	NOT NULL	FOREIGN KEY REFERENCES TicketSituacao(ID),
	Codigo				INT			NOT NULL,				
	DataAbertura		DATETIME	NOT NULL	DEFAULT GETDATE(),
	DataConclusao		DATETIME,
)

CREATE TABLE TicketAnotacao(
	ID			BIGINT			NOT NULL	PRIMARY KEY,
	IdTicket	BIGINT			NOT NULL	FOREIGN KEY REFERENCES Ticket(Id),
	IdUsuario	BIGINT			NOT NULL	FOREIGN KEY REFERENCES Usuario(Id),
	Texto		VARCHAR(512)	DEFAULT	'Sem anotações para este Ticket.',
	[Data]		DATETIME		NOT NULL	DEFAULT GETDATE()
)

